print('========== DESAFIO 10 ==========')
dia = input('Dia = ')
mes = input('Mês = ')
ano = input('Ano = ')
print('Você nasceu no dia ', dia, ' do mês ', mes, ' no ano de ', ano, ' , correto?')
print(dia, '/', mes, '/', ano)
