print('========== DESAFIO 13 ==========')
print('>> LIQUIDAÇÃO (%) <<')
p = float(input('Valor do produto: R$'))
des5 = p - (p * 0.05)
des10 = p - (p * 0.10)
des15 = p - (p * 0.15)
des20 = p - (p * 0.20)
print('Valor com desconto (5%): R${:.2f}'.format(des5))
print('Valor com desconto (10%): R${:.2f}'.format(des10))
print('Valor com desconto (15%): R${:.2f}'.format(des15))
print('Valor com desconto (20%): R${:.2f}'.format(des20))
