x = input('Digite algo: ')
print('O tipo definitivo desse valor é ', type(x))
print('É somente número? ', x.isnumeric())
print('É somente letra? ', x.isalpha())
print('É alfanúmerico? ', x.isalnum())
print('Só tem espaços? ', x.isspace())
print('Está em maiusculas? ', x.isupper())
print('Está em minusculas? ', x.islower())
print('Está captalizada? ', x.istitle())
